bcgov/nrts-prc-admin

- src/app/administration/users/add-edit-user/add-edit-user.component.html
- src/app/administration/users/add-edit-user/add-edit-user.component.scss
- src/app/administration/users/add-edit-user/add-edit-user.component.spec.ts
- src/app/administration/users/add-edit-user/add-edit-user.component.ts
- src/app/administration/users/users.component.html
- src/app/administration/users/users.component.scss
- src/app/administration/users/users.component.ts
- src/app/app.module.ts
- src/app/models/user.ts
- src/app/services/api.ts
- src/app/services/user.service.ts
Adding new user, styling changes.
> PRC-111: Adding administrative user management - edit/save.

- src/app/administration/users/users.component.ts
- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-detail/application-detail.component.ts
- src/app/applications/application-list/application-list.component.html
- src/app/applications/application-list/application-list.component.ts
- src/app/commenting/commenting-routing.module.ts
- src/app/commenting/manage-comment-periods/manage-comment-periods.component.html
- src/app/commenting/manage-comment-periods/manage-comment-periods.component.ts
- src/app/commenting/review-comments/add-comment/add-comment.component.ts
- src/app/commenting/review-comments/comment-detail/comment-detail.component.ts
- src/app/commenting/review-comments/review-comments.component.html
- src/app/commenting/review-comments/review-comments.component.ts
- src/app/services/application.service.ts
- src/app/services/comment.service.ts
- src/app/services/commentperiod.service.ts
- src/app/services/organization.service.ts
NOBUG: deleted/commented out obsolete code
> PRC-80: changed to queryParams + lots of cleanup

- package.json
- src/app/applications/application-detail/application-detail.component.ts
- src/app/applications/application-list/application-list.component.ts
- src/app/commenting/manage-comment-periods/manage-comment-periods.component.ts
- src/app/commenting/review-comments/review-comments.component.ts
also added package needed for ng cli to work
> BUG: changed to public methods that needed it

- src/app/applications/application-add-edit/application-add-edit.component.ts
- src/app/services/application.service.ts
+ Error handling for projectDate
> PRC-88: Adjustment of a few import fields.

- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-add-edit/application-add-edit.component.ts
- src/app/models/application.ts
- src/app/services/api.ts
- src/app/services/application.service.ts
> PRC-128: Publish/unpublish applications

- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-detail/application-detail.component.scss
- src/app/applications/application-detail/application-detail.component.ts
- src/app/map/esri-map/esri-map.component.scss
- src/assets/styles/components/aside.scss
- src/assets/styles/components/buttons.scss
- src/assets/styles/themes/typography.scss
Front-end Development Progress Commit.
> [PRC-226] Application Details Page

- src/app/applications/application-add-edit/application-add-edit.component.ts
- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-detail/application-detail.component.scss
- src/app/applications/application-detail/application-detail.component.ts
- src/app/commenting/manage-comment-periods/add-edit-comment-period/add-edit-comment-period.component.html
- src/app/commenting/manage-comment-periods/add-edit-comment-period/add-edit-comment-period.component.ts
- src/app/commenting/review-comments/review-comments.component.scss
- src/app/models/decision.ts
- src/app/services/api.ts
also deleted decision.decisionDate
> PRC-99: added decision and other stuff to app details (WIP)

- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-detail/application-detail.component.scss
- src/app/applications/application-detail/application-detail.component.ts
- src/app/models/application.ts
- src/app/services/api.ts
- src/app/services/application.service.ts
- src/app/services/search.service.ts
PRC-226: Adding in shape referencing/meta import on the fly.
Merge from upstream.
PRC-88: Adding in areaHectares as a calculated field.
> PRC-226, PRC-88:

- src/app/applications/application-add-edit/application-add-edit.component.ts
- src/app/commenting/commenting.module.ts
- src/app/commenting/review-comments/comment-detail/comment-detail.component.html
- src/app/confirm/confirm.component.html
- src/app/services/application.service.ts
- added support for HTML in Confirm component title and message
- hard-coded Region="Skeena" when adding application (via Search or New)
> PRC-252: commented out some boilerplate app properties (WIP) + misc tweaks

- src/app/applications/application-add-edit/application-add-edit.component.scss
- src/app/applications/application-aside/application-aside.component.html
- src/app/applications/application-list/application-list.component.html
- src/app/applications/application-list/application-list.component.ts
- src/app/home/home.component.html
- src/app/models/application.ts
- src/app/services/application.service.ts
- src/app/services/commentperiod.service.ts
- src/assets/styles/components/accordion.scss
These are legitimate refactoring-type changes (same as Public project).
> PRC-307: saved query param in URL (re: history) + ported service changes from Public to Admin

- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-add-edit/application-add-edit.component.ts
- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-list/application-list.component.html
- src/app/applications/application-list/application-list.component.ts
- src/app/home/home.component.ts
- src/app/models/search.ts
- src/app/search/search.component.ts
- src/app/services/api.ts
- src/app/services/application.service.ts
>  Merge branch 'prc460' of github.com:severinbeauvais/nrts-prc-admin into scale

- src/app/applications/application-list/application-list.component.html
- src/assets/styles/components/pagination.scss
- Updated styles for existing pagination control
- Removed unused/legacy pagination styles
- Moved pagination control to the bottom of the application list
> [PRC-498] Pagination UI Clean-up

- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-add-edit/application-add-edit.component.scss
- src/app/applications/application-aside/application-aside.component.scss
- src/app/applications/application-aside/application-aside.component.ts
- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-detail/application-detail.component.scss
- src/app/applications/application-list/application-list.component.html
- src/app/applications/select-organization/select-organization.component.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/services/api.ts
- src/assets/styles/components/badge.scss
- src/assets/styles/components/buttons.scss
- src/assets/styles/components/doc-list.scss
- src/assets/styles/components/form-elements.scss
- src/assets/styles/layout/layout.scss
- src/styles.scss
Updated the publish/unpublish buttons for application and decision documents.
- Update/cleaned up the document list styling
- Added global/reusable styles for document list
- WS fixes
> [PRC-507] Update Publish/Unpublish Buttons

- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-add-edit/application-add-edit.component.scss
- src/app/applications/application-aside/application-aside.component.scss
- src/app/applications/application-detail/application-detail.component.html
- src/app/applications/application-detail/application-detail.component.scss
- src/app/applications/application-list/application-list.component.html
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/assets/styles/components/badge.scss
- src/assets/styles/components/buttons.scss
- src/assets/styles/components/doc-list.scss
- src/assets/styles/components/form-elements.scss
- src/assets/styles/layout/layout.scss
- src/styles.scss
Updating/Refactoring the Application Document Publish interface components to provide clearer description on the intended functionality.
Additional Fixes/Updates
- white-space fixes for various SCSS files
- fixed markup issue in the Header Component (brand image and badge)
> [PRC-507] Update Publish Buttons

- src/app/app-routing.module.ts
- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-add-edit/application-add-edit.component.ts
- src/app/applications/application-detail/application-detail.component.ts
- src/app/commenting/manage-comment-periods/manage-comment-periods.component.ts
- src/app/commenting/review-comments/review-comments.component.ts
- src/app/header/header.component.html
- src/app/search/search.component.scss
- src/app/search/search.component.ts
Changed the default route to the 'Find Applications' page, and updated the main navigation to reflect the new name of the page.
Additional Updates
- Fixed search redirect when not logged in
- Change redirects from App List page to Search page
- Minor styling tweak to the search form interface
> [PRC-591] Update Header Navigation and Default Route

- package.json
- src/app/search/search.component.ts
- src/app/services/api.ts
Redirect to login page if expired.
> PRC-643: Check JWT token expiry.

- src/app/services/commentperiod.service.ts
Reverts bcgov/nrts-prc-admin#219
> Revert "DEBUG: only use first comment period"

- src/app/applications/application-aside/application-aside.component.scss
- src/app/applications/application-detail/application-detail.component.scss
- src/assets/styles/base/base.scss
- src/assets/styles/components/form-elements.scss
- src/styles.scss
General UI code cleanup
- Removed various imports from BASE and relocated them to our global STYLES file to avoid replication when compiling the application style sheet
- Tightened up the vertical spacing in the Application Create/Edit views
> [PRC-704] UI Clean-up

- src/app/commenting/review-comments/comment-detail/comment-detail.component.html
- src/app/commenting/review-comments/comment-detail/comment-detail.component.scss
- src/app/commenting/review-comments/comment-detail/comment-detail.component.ts
- src/app/commenting/review-comments/review-comments.component.html
- src/app/commenting/review-comments/review-comments.component.scss
- src/app/commenting/review-comments/review-comments.component.ts
- src/app/services/comment.service.ts
- src/assets/styles/base/typography.scss
- src/assets/styles/components/doc-list.scss
- src/assets/styles/components/form-elements.scss
- src/assets/styles/components/pagination.scss
- src/assets/styles/layout/layout.scss
Updating the Review Comment Interface to conform to new design standards.
Additional / Related Issues
[PRC-779] Updated comment service to return documents for all comments + misc fixes
[PRC-536] Provide visual to identify which comments have attachments
Miscellaneous styling tweaks / UI updates (spacing, etc.)
> [PRC-756] Review Comment UI Update

- src/app/search/search.component.html
- src/app/search/search.component.scss
Fixed an issue where the column widths were preventing the table from sizing correctly on smaller monitor resolutions. Minor styling adjustments / small markup changes only.
> [PRC-794] Fix Overlapping Table Columns

- package.json
- src/app/administration/users/add-edit-user/add-edit-user.component.spec.ts
- src/app/administration/users/users.component.spec.ts
- src/app/app.component.spec.ts
- src/app/applications/application-add-edit/application-add-edit.component.spec.ts
- src/app/applications/application-aside/application-aside.component.spec.ts
- src/app/applications/application-detail/application-detail.component.spec.ts
- src/app/applications/application-list/application-list.component.spec.ts
- src/app/applications/application-resolver.service.spec.ts
- src/app/applications/review-comments/comment-detail/comment-detail.component.spec.ts
- src/app/applications/review-comments/review-comments.component.spec.ts
- src/app/confirm/confirm.component.spec.ts
- src/app/header/header.component.spec.ts
- src/app/home/home.component.spec.ts
- src/app/login/login.component.spec.ts
- src/app/not-authorized/not-authorized.component.spec.ts
- src/app/search/search.component.spec.ts
- src/app/select-organization/select-organization.component.spec.ts
- src/app/services/application.service.spec.ts
- src/app/services/comment.service.spec.ts
- src/app/services/commentperiod.service.spec.ts
- src/app/services/decision.service.spec.ts
- src/app/services/document.service.spec.ts
- src/app/services/feature.service.spec.ts
- src/app/services/organization.service.spec.ts
- src/app/services/search.service.spec.ts
- src/app/services/user.service.spec.ts
- src/app/utils/ng-var.directive.spec.ts
- Fix existing unit tests
- Write new ones around complicated Services
- update `npm test` command to be a no-op so it does not run in build.
> Get admin test suite running

- src/app/applications/review-comments/review-comments.component.spec.ts
- src/app/search/search.component.spec.ts
- src/app/spec/helpers.ts
Fixed a handful of linting errors.
- I also ran the formatter, which is why so many lines appear changed.  Probably should have put those in a separate commit.
No code changes of any kind.
> NOBUG: fix linting issues.

- src/app/applications/application-add-edit/application-add-edit.component.html
Fixing named anchor link to decision section of the edit page.
> [PRC-974] Fixed Named Anchor Issue

- src/app/applications/application-add-edit/application-add-edit.component.html
- src/app/applications/application-add-edit/application-add-edit.component.scss
- src/app/applications/application-detail/application-detail.component.html
- src/app/models/decision.ts
- src/app/services/decision.service.ts
Removed the decision description code, and removed it from the model.
- I haven't written anything to purge the existing decision descriptions from the database.  Can do that as its own task.
Also removed some random scss that was not referenced anywhere in the code.
> PRC-1029: Remove decision description from UI and model. 

- src/app/applications/application-aside/application-aside.component.ts
Fix an issue that had no impact on the user but created an error message in the console.
> NOBUG: Fix trivial console error message.
